config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get :new_application, to: "candidates#new_application"
  post :apply, to: "candidates#apply"

  namespace :cosa do
    root to: "dashboard#index"
    resources :candidates

    get "login", to: "sessions#new", as: "login"
    delete "logout", to: "sessions#destroy", as: "logout"
    match "/auth/:provider/callback", to: "sessions#create", via: [:post, :get]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates :name, :last_name, :location, :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :email, :nickname, presence: true
  enum role: [ :admin, :recruitment, :user ]

  def self.find_or_create_from_auth_hash(user_hash)
    info = user_hash.info
    email = info.email

    user = User.find_by(email: email)
    # fail if the user is not found and it's not a super admin email
    return nil unless user || SUPER_ADMIN_EMAILS.include?(email)

    # create users for super admins if needed
    user ||= User.new(email: email)

    # update personal info
    user.name = info.name
    user.image = info.image
    user.nickname = user_hash.provider == "github" ? info.nickname : info.github_nickname

    # set role as :user by default unless already set or super admin
    user.role ||= SUPER_ADMIN_EMAILS.include?(email) ? :admin : :user

    user.save!
    
    # TODO: store login somewhere (maybe an Activity model)

    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  include Pagy::Backend
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def new_application
    @candidate = Candidate.new
  end

  def apply
    @candidate = Candidate.find_or_initialize_by(email: params[:candidate][:email])
    @candidate.update(candidate_params)

    if @candidate.invalid?
      render :new_application, error: "We could not process your application"
    end
  end

  private

  def candidate_params
    params.require(:candidate).permit(:name, :last_name, :email, :location)
  end
end

app/controllers/cosa/cosa_controller.rb
class Cosa::CosaController < ApplicationController
  before_action :require_user

  layout "cosa"

  private

  def require_user
    current_user_id = session[:cosa_current_user_id]
    unless current_user_id
      redirect_to cosa_login_path and return
    end

    @current_user = User.find_by(id: current_user_id)
    unless @current_user
      redirect_to cosa_login_path and return
    end
  end
end

app/controllers/cosa/dashboard_controller.rb
class Cosa::DashboardController < Cosa::CosaController
  def index
  end
end

app/controllers/cosa/sessions_controller.rb
class Cosa::SessionsController < Cosa::CosaController
  skip_before_action :require_user
  skip_before_action :verify_authenticity_token, only: :create

  def new
  end

  def create
    user = User.find_or_create_from_auth_hash(auth_hash)
    session[:cosa_current_user_id] = user.id
    redirect_to cosa_root_path
  end

  def destroy
    @current_user = nil
    session[:cosa_current_user_id] = nil
    redirect_to cosa_login_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/cosa_helper.rb
module CosaHelper
  def current_user
    @current_user
  end

  def logged_in?
    current_user.present?
  end
end

app/views/candidates/apply.html.slim
h1 Thank you for applying!

app/views/candidates/new_application.html.slim
h1 Apply to some position 

= form_for @candidate, url: apply_path, method: :post do |f|
  .field
    = f.label :name
    = f.text_field :name, required: true
    - if @candidate.errors[:name].any?
      .errors= @candidate.errors[:name]
  .field
    = f.label :last_name
    = f.text_field :last_name, required: true
    - if @candidate.errors[:last_name].any?
      .errors= @candidate.errors[:last_name]
  .field
    = f.label :email
    = f.email_field :email, required: true
    - if @candidate.errors[:email].any?
        .errors= @candidate.errors[:email]
  .field
    = f.label :location, "Location or timezone"
    = f.text_field :location, required: true
    - if @candidate.errors[:location].any?
      .errors= @candidate.errors[:location]

  = f.submit "Apply"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CosaHQ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/cosa.html.slim
doctype html

html
  head
    title CosaHQ
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    nav
      - if logged_in?
        = button_to "log out", cosa_logout_path, method: :delete

    = yield